VIDEO_TITLE = ENV["TITLE"]

CONVERSATION_INTERVAL = 0.3
CUSTOM_BR_CODE = "{br}"

MERGED_AUDIO_FILENAME = "merged.mp3"
COVER_IMAGE_FILENAME = "cover.png"
OUTPUT_VIDEO_FILENAME = "video.mp4"
SUBTITLE_INPUT_FILENAME = "subtitle.csv"
SUBTITLE_OUTPUT_FILENAME = "subtitle.ass"

class VideoGenerator
  def initialize(title:)
    @title = title

    @dirname = [`echo $HOME`.chomp, "Movies/voicevox/#{VIDEO_TITLE}"].join("/")
  end

  def run
    validate!
    clear_existing_outputs
    merge_audio
    generate_subtitle
    generate_video
  end

  def validate!
    if VIDEO_TITLE.nil?
      raise "Argument TITLE= is not set."
    end

    unless Dir.exist?(dirname)
      raise "Directory #{dirname} does not exist."
    end

    unless File.exist?(File.join(dirname, COVER_IMAGE_FILENAME))
      raise "Cover image file #{COVER_IMAGE_FILENAME} does not exist in #{dirname}."
    end

    unless File.exist?(File.join(dirname, SUBTITLE_INPUT_FILENAME))
      raise "Subtitle input file #{SUBTITLE_INPUT_FILENAME} does not exist in #{dirname}."
    end

    true
  end

  def clear_existing_outputs
    if File.exist?(File.join(dirname, MERGED_AUDIO_FILENAME))
      File.delete(File.join(dirname, MERGED_AUDIO_FILENAME))
    end

    if File.exist?(File.join(dirname, SUBTITLE_OUTPUT_FILENAME))
      File.delete(File.join(dirname, SUBTITLE_OUTPUT_FILENAME))
    end

    if File.exist?(File.join(dirname, OUTPUT_VIDEO_FILENAME))
      File.delete(File.join(dirname, OUTPUT_VIDEO_FILENAME))
    end
  end

  def merge_audio_command
    audio_inputs = audio_filepaths.map { |filepath| "-i #{filepath}" }.join(" ")

    # "[0:a][s][1:a][s][2:a]concat=n=5:v=0:a=1[out]"
    merge_option = audio_filepaths.map.with_index do |_, index|
      "[#{index}:a][s#{index}]"
    end.join("") + "concat=n=#{audio_filepaths.length * 2}"

    silence_option = audio_filepaths.length.times.map.with_index { |i| "[s#{i}]" }.join("")
    output_path = File.join(dirname, MERGED_AUDIO_FILENAME)

    "ffmpeg #{audio_inputs} -filter_complex \"anullsrc=r=44100:cl=stereo:d=0.2,asplit=#{audio_filepaths.length}#{silence_option}; #{merge_option}:v=0:a=1[out]\" -map \"[out]\" #{output_path}"
  end

  def merge_audio
    `#{merge_audio_command}`
  end

  def generate_subtitle
    script_info_section = [
      "[Script Info]",
      "; Script generated by FFmpeg/Lavc61.19.101",
      "ScriptType: v4.00+",
      "PlayResX: 384",
      "PlayResY: 288",
      "ScaledBorderAndShadow: yes",
      "YCbCr Matrix: None",
    ].join("\n")

    style_section = [
      "[V4+ Styles]",
      "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
      "Style: Default,Arial,12,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1",
      "Style: Green,Arial,12,&H00E676,&H00E676,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1",
      "Style: Pink,Arial,12,&HFF80AB,&HFF80AB,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1",
    ].join("\n")

    event_section = ([
      "[Events]",
      "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ] + subtitle_audio_section).join("\n")

    file_body = [script_info_section, style_section, event_section].join("\n\n")

    # generate text file named subtitle.ass
    File.open(File.join(dirname, SUBTITLE_OUTPUT_FILENAME), "w") do |file|
      file.write(file_body)
    end

    true
  end

  def subtitle_audio_section
    file_data = audio_filepaths.map do |filepath|
      # get audio length in seconds
      length = `ffprobe -i "#{filepath}" -show_entries format=duration -v quiet -of csv="p=0"`.to_f

      { filepath: filepath, length: length }
    end

    # get CSV data for subtitle file
    csv_body = File.read(File.join(dirname, SUBTITLE_INPUT_FILENAME))
    csv_rows = csv_body.split("\n")

    subtitles = csv_rows.map.with_index do |row, i|
      speaker, text = row.split(",")

      { speaker: speaker, text: text }
    end

    prev_end_time = 0.3
    dialogues = file_data.map.with_index do |data, i|
      interval = CONVERSATION_INTERVAL * 0.7
      start_time = i > 0 ? prev_end_time + interval : prev_end_time
      end_time = start_time + data[:length]

      prev_end_time = end_time

      style = case true
        when subtitles[i][:speaker].include?("四国めたん")
          "Pink"
        when subtitles[i][:speaker].include?("ずんだもん")
          "Green"
        else
          "Default"
        end

      text = subtitles[i][:text].gsub(CUSTOM_BR_CODE, "\\n")

      "Dialogue: " + [
        "0", # Layer
        format_time(start_time),
        format_time(end_time),
        style, # Style
        "", # Name
        "0", # MarginL
        "0", # MarginR
        "0", # MarginV
        "", # Effect
        text, # Text
      ].join(",")
    end

    dialogues
  end

  def generate_video_command
    output_path = File.join(dirname, OUTPUT_VIDEO_FILENAME)
    cover_image_path = File.join(dirname, COVER_IMAGE_FILENAME)
    merged_audio_path = File.join(dirname, MERGED_AUDIO_FILENAME)
    subtitle_file_path = File.join(dirname, SUBTITLE_OUTPUT_FILENAME)

    "ffmpeg -loop 1 -i #{cover_image_path} -i #{merged_audio_path} -vf \"ass=#{subtitle_file_path}\" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -shortest -pix_fmt yuv420p #{output_path}"
  end

  def generate_video
    `#{generate_video_command}`
  end

  private
  attr_reader :dirname

  def audio_filepaths
    @audio_filepaths ||= Dir.glob("#{dirname}/*.wav")
  end

  def get_audio_length(filepath)
    `ffprobe -i "#{filepath}" -show_entries format=duration -v quiet -of csv="p=0"`.to_f
  end

  def format_time(seconds)
    hours = (seconds / 3600).to_i
    minutes = ((seconds % 3600) / 60).to_i
    secs = (seconds % 60).to_i
    milliseconds = ((seconds - seconds.to_i) * 100).to_i

    format("%01d:%02d:%02d.%02d", hours, minutes, secs, milliseconds)
  end
end

VideoGenerator.new(title: VIDEO_TITLE).run
