class GenerateVideoBaseService
  CONVERSATION_INTERVAL = 0.2
  CUSTOM_BR_CODE = "{br}"
  PLAY_RES_X = 384
  FONT_SIZE   = 12

  VideoSubtitle = Struct.new(:start_time_sec, :end_time_sec, :speaker, :text, :style)

  def initialize(dir)
    @dir = dir
  end

  def merge_audio_files(wav_files)
    audio_inputs  = wav_files.map { |f| "-i #{Shellwords.escape(f)}" }.join(" ")
    silence_parts = wav_files.length.times.map { |i| "[s#{i}]" }.join("")
    merge_parts   = wav_files.each_with_index.map { |_, i| "[#{i}:a][s#{i}]" }.join("")
    output_path   = Shellwords.escape(File.join(@dir, "merged.mp3"))

    cmd = "ffmpeg #{audio_inputs} " \
          "-filter_complex \"anullsrc=r=44100:cl=stereo:d=#{CONVERSATION_INTERVAL}," \
          "asplit=#{wav_files.length}#{silence_parts}; " \
          "#{merge_parts}concat=n=#{wav_files.length * 2}:v=0:a=1[out]\" " \
          "-map \"[out]\" #{output_path}"
    system(cmd)
  end

  def parse_subtitles(wav_files)
    csv_rows = File.read(File.join(@dir, "subtitle.csv")).split("\n")

    prev_end_time = CONVERSATION_INTERVAL
    wav_files.each_with_index.map do |filepath, i|
      length = `ffprobe -i #{Shellwords.escape(filepath)} -show_entries format=duration -v quiet -of csv="p=0"`.to_f

      speaker, text = csv_rows[i].split(",")
      text          = yield(text) if block_given?
      start_time    = i > 0 ? prev_end_time + CONVERSATION_INTERVAL : prev_end_time
      end_time      = start_time + length
      prev_end_time = end_time

      style = if speaker.include?("四国めたん") then "Pink"
              elsif speaker.include?("ずんだもん") then "Green"
              else "Default"
              end

      VideoSubtitle.new(start_time, end_time, speaker, text, style)
    end
  end

  def write_ass_subtitle(subtitles)
    script_info = <<~ASS.chomp
      [Script Info]
      ; Script generated by FFmpeg/Lavc61.19.101
      ScriptType: v4.00+
      PlayResX: 384
      PlayResY: 288
      ScaledBorderAndShadow: yes
      YCbCr Matrix: None
    ASS

    style_section = <<~ASS.chomp
      [V4+ Styles]
      Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
      Style: Default,Noto Sans CJK JP,12,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
      Style: Green,Noto Sans CJK JP,12,&H00E676,&H00E676,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
      Style: Pink,Noto Sans CJK JP,12,&HFF80AB,&HFF80AB,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
    ASS

    dialogues = subtitles.map do |sub|
      "Dialogue: " + [
        "0",
        format_ass_time(sub.start_time_sec),
        format_ass_time(sub.end_time_sec),
        sub.style,
        "", "0", "0", "0", "",
        sub.text.gsub(CUSTOM_BR_CODE, "\\n"),
      ].join(",")
    end

    event_section = ([
      "[Events]",
      "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ] + dialogues).join("\n")

    File.write(File.join(@dir, "subtitle.ass"), [script_info, style_section, event_section].join("\n\n"))
  end

  def write_srt_subtitle(subtitles)
    content = subtitles.each_with_index.map do |sub, i|
      [
        i.to_s,
        "#{format_srt_time(sub.start_time_sec)} --> #{format_srt_time(sub.end_time_sec)}",
        sub.text.gsub(CUSTOM_BR_CODE, "\n"),
      ].join("\n")
    end.join("\n\n")

    File.write(File.join(@dir, "subtitle.srt"), content)
  end

  def append_ending_image(ending_image_path, duration = 3)
    video_path   = File.join(@dir, "video.mp4")
    temp_path    = File.join(@dir, "video_main.mp4")
    ending_path  = File.join(@dir, "video_ending.mp4")
    concat_file  = File.join(@dir, "concat_list.txt")

    File.rename(video_path, temp_path)

    dimensions = `ffprobe -v quiet -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 #{Shellwords.escape(temp_path)}`.strip
    width, height = dimensions.split("x").map(&:to_i)

    audio_info = `ffprobe -v quiet -select_streams a:0 -show_entries stream=sample_rate,channels -of csv=p=0 #{Shellwords.escape(temp_path)}`.strip
    sample_rate, channels = audio_info.split(",").map(&:to_i)
    channel_layout = channels == 1 ? "mono" : "stereo"

    ending_cmd = "ffmpeg -loop 1 -t #{duration} -i #{Shellwords.escape(ending_image_path)} " \
                 "-f lavfi -t #{duration} -i anullsrc=r=#{sample_rate}:cl=#{channel_layout} " \
                 "-vf \"scale=#{width}:#{height}:force_original_aspect_ratio=decrease,pad=#{width}:#{height}:(ow-iw)/2:(oh-ih)/2\" " \
                 "-c:v libx264 -bf 0 -c:a alac -pix_fmt yuv420p -shortest #{Shellwords.escape(ending_path)}"
    system(ending_cmd)

    File.write(concat_file, "file '#{temp_path}'\nfile '#{ending_path}'\n")

    concat_cmd = "ffmpeg -f concat -safe 0 -i #{Shellwords.escape(concat_file)} -c copy #{Shellwords.escape(video_path)}"
    system(concat_cmd)

    File.delete(temp_path) if File.exist?(temp_path)
    File.delete(ending_path) if File.exist?(ending_path)
    File.delete(concat_file) if File.exist?(concat_file)
  end

  private

  def format_ass_time(seconds)
    h  = (seconds / 3600).to_i
    m  = ((seconds % 3600) / 60).to_i
    s  = (seconds % 60).to_i
    cs = ((seconds - seconds.to_i) * 100).to_i
    format("%01d:%02d:%02d.%02d", h, m, s, cs)
  end

  def format_srt_time(seconds)
    h  = (seconds / 3600).to_i
    m  = ((seconds % 3600) / 60).to_i
    s  = (seconds % 60).to_i
    ms = ((seconds - seconds.to_i) * 1000).to_i
    format("%01d:%02d:%02d,%03d", h, m, s, ms)
  end
end
