class GenerateVideoService
  CONVERSATION_INTERVAL = 0.2
  CUSTOM_BR_CODE = "{br}"

  VideoSubtitle = Struct.new(:start_time_sec, :end_time_sec, :speaker, :text, :style)

  def initialize(dir)
    @dir = dir
  end

  def call
    validate_video_inputs!

    wav_files = Dir.glob(File.join(@dir, "*.wav")).sort

    clear_video_outputs
    merge_audio_files(wav_files)

    subtitles = parse_subtitles(wav_files)
    write_ass_subtitle(subtitles)
    write_srt_subtitle(subtitles)

    assemble_video

    File.join(@dir, "video.mp4")
  end

  private

  def validate_video_inputs!
    raise "Directory not found: #{@dir}" unless Dir.exist?(@dir)

    has_cover  = File.exist?(File.join(@dir, "cover.png"))
    has_slides = File.exist?(File.join(@dir, "google-slides.json"))
    raise "cover.png or google-slides.json is required in #{@dir}" unless has_cover || has_slides

    if has_slides
      slides = JSON.parse(File.read(File.join(@dir, "google-slides.json")))
      slides.each do |slide|
        path = File.expand_path(slide["thumbnail"].to_s, @dir)
        raise "thumbnail not found: #{path}" unless File.exist?(path)
      end
    end

    raise "subtitle.csv not found in #{@dir}" unless File.exist?(File.join(@dir, "subtitle.csv"))
    raise "No .wav files found in #{@dir}" if Dir.glob(File.join(@dir, "*.wav")).empty?
  end

  def clear_video_outputs
    %w[merged.mp3 subtitle.ass subtitle.srt video.mp4].each do |f|
      path = File.join(@dir, f)
      File.delete(path) if File.exist?(path)
    end
  end

  def merge_audio_files(wav_files)
    audio_inputs  = wav_files.map { |f| "-i #{Shellwords.escape(f)}" }.join(" ")
    silence_parts = wav_files.length.times.map { |i| "[s#{i}]" }.join("")
    merge_parts   = wav_files.each_with_index.map { |_, i| "[#{i}:a][s#{i}]" }.join("")
    output_path   = Shellwords.escape(File.join(@dir, "merged.mp3"))

    cmd = "ffmpeg #{audio_inputs} " \
          "-filter_complex \"anullsrc=r=44100:cl=stereo:d=#{CONVERSATION_INTERVAL}," \
          "asplit=#{wav_files.length}#{silence_parts}; " \
          "#{merge_parts}concat=n=#{wav_files.length * 2}:v=0:a=1[out]\" " \
          "-map \"[out]\" #{output_path}"
    system(cmd)
  end

  def cover_image_path
    return File.join(@dir, "cover.png") if File.exist?(File.join(@dir, "cover.png"))

    slides = JSON.parse(File.read(File.join(@dir, "google-slides.json")))
    thumbnail = slides.dig(0, "thumbnail") || raise("thumbnail not found in google-slides.json")
    File.expand_path(thumbnail, @dir)
  end

  def assemble_video
    cover    = Shellwords.escape(cover_image_path)
    audio    = Shellwords.escape(File.join(@dir, "merged.mp3"))
    subtitle = File.join(@dir, "subtitle.ass")
    output   = Shellwords.escape(File.join(@dir, "video.mp4"))

    system("ffmpeg -loop 1 -i #{cover} -i #{audio} -vf \"ass=#{subtitle}\" " \
           "-c:v libx264 -tune stillimage -c:a aac -b:a 192k -shortest -pix_fmt yuv420p #{output}")
  end

  def parse_subtitles(wav_files)
    csv_rows = File.read(File.join(@dir, "subtitle.csv")).split("\n")

    prev_end_time = CONVERSATION_INTERVAL
    wav_files.each_with_index.map do |filepath, i|
      length = `ffprobe -i #{Shellwords.escape(filepath)} -show_entries format=duration -v quiet -of csv="p=0"`.to_f

      speaker, text = csv_rows[i].split(",")
      start_time    = i > 0 ? prev_end_time + CONVERSATION_INTERVAL : prev_end_time
      end_time      = start_time + length
      prev_end_time = end_time

      style = if speaker.include?("四国めたん") then "Pink"
              elsif speaker.include?("ずんだもん") then "Green"
              else "Default"
              end

      VideoSubtitle.new(start_time, end_time, speaker, text, style)
    end
  end

  def write_ass_subtitle(subtitles)
    script_info = <<~ASS.chomp
      [Script Info]
      ; Script generated by FFmpeg/Lavc61.19.101
      ScriptType: v4.00+
      PlayResX: 384
      PlayResY: 288
      ScaledBorderAndShadow: yes
      YCbCr Matrix: None
    ASS

    style_section = <<~ASS.chomp
      [V4+ Styles]
      Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
      Style: Default,Noto Sans CJK JP,12,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
      Style: Green,Noto Sans CJK JP,12,&H00E676,&H00E676,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
      Style: Pink,Noto Sans CJK JP,12,&HFF80AB,&HFF80AB,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
    ASS

    dialogues = subtitles.map do |sub|
      "Dialogue: " + [
        "0",
        format_ass_time(sub.start_time_sec),
        format_ass_time(sub.end_time_sec),
        sub.style,
        "", "0", "0", "0", "",
        sub.text.gsub(CUSTOM_BR_CODE, "\\n"),
      ].join(",")
    end

    event_section = ([
      "[Events]",
      "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ] + dialogues).join("\n")

    File.write(File.join(@dir, "subtitle.ass"), [script_info, style_section, event_section].join("\n\n"))
  end

  def write_srt_subtitle(subtitles)
    content = subtitles.each_with_index.map do |sub, i|
      [
        i.to_s,
        "#{format_srt_time(sub.start_time_sec)} --> #{format_srt_time(sub.end_time_sec)}",
        sub.text.gsub(CUSTOM_BR_CODE, "\n"),
      ].join("\n")
    end.join("\n\n")

    File.write(File.join(@dir, "subtitle.srt"), content)
  end

  def format_ass_time(seconds)
    h  = (seconds / 3600).to_i
    m  = ((seconds % 3600) / 60).to_i
    s  = (seconds % 60).to_i
    cs = ((seconds - seconds.to_i) * 100).to_i
    format("%01d:%02d:%02d.%02d", h, m, s, cs)
  end

  def format_srt_time(seconds)
    h  = (seconds / 3600).to_i
    m  = ((seconds % 3600) / 60).to_i
    s  = (seconds % 60).to_i
    ms = ((seconds - seconds.to_i) * 1000).to_i
    format("%01d:%02d:%02d,%03d", h, m, s, ms)
  end
end
