class GenerateVideoBaseService
  CONVERSATION_INTERVAL = 0.2
  CUSTOM_BR_CODE = "{br}"
  PLAY_RES_X = 384
  FONT_SIZE   = 12

  VideoSubtitle = Struct.new(:start_time_sec, :end_time_sec, :speaker, :text, :style)

  def initialize(dir)
    @dir = dir
  end

  def merge_audio_files(wav_files)
    audio_inputs  = wav_files.map { |f| "-i #{Shellwords.escape(f)}" }.join(" ")
    silence_parts = wav_files.length.times.map { |i| "[s#{i}]" }.join("")
    merge_parts   = wav_files.each_with_index.map { |_, i| "[#{i}:a][s#{i}]" }.join("")
    output_path   = Shellwords.escape(File.join(@dir, "merged.mp3"))

    cmd = "ffmpeg #{audio_inputs} " \
          "-filter_complex \"anullsrc=r=44100:cl=stereo:d=#{CONVERSATION_INTERVAL}," \
          "asplit=#{wav_files.length}#{silence_parts}; " \
          "#{merge_parts}concat=n=#{wav_files.length * 2}:v=0:a=1[out]\" " \
          "-map \"[out]\" #{output_path}"
    system(cmd)
  end

  def parse_subtitles(wav_files)
    csv_rows = File.read(File.join(@dir, "subtitle.csv")).split("\n")

    prev_end_time = CONVERSATION_INTERVAL
    wav_files.each_with_index.map do |filepath, i|
      length = `ffprobe -i #{Shellwords.escape(filepath)} -show_entries format=duration -v quiet -of csv="p=0"`.to_f

      speaker, text = csv_rows[i].split(",")
      text          = yield(text) if block_given?
      start_time    = i > 0 ? prev_end_time + CONVERSATION_INTERVAL : prev_end_time
      end_time      = start_time + length
      prev_end_time = end_time

      style = if speaker.include?("四国めたん") then "Pink"
              elsif speaker.include?("ずんだもん") then "Green"
              else "Default"
              end

      VideoSubtitle.new(start_time, end_time, speaker, text, style)
    end
  end

  def write_ass_subtitle(subtitles)
    script_info = <<~ASS.chomp
      [Script Info]
      ; Script generated by FFmpeg/Lavc61.19.101
      ScriptType: v4.00+
      PlayResX: 384
      PlayResY: 288
      ScaledBorderAndShadow: yes
      YCbCr Matrix: None
    ASS

    style_section = <<~ASS.chomp
      [V4+ Styles]
      Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
      Style: Default,Noto Sans CJK JP,12,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
      Style: Green,Noto Sans CJK JP,12,&H00E676,&H00E676,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
      Style: Pink,Noto Sans CJK JP,12,&HFF80AB,&HFF80AB,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
    ASS

    dialogues = subtitles.map do |sub|
      "Dialogue: " + [
        "0",
        format_ass_time(sub.start_time_sec),
        format_ass_time(sub.end_time_sec),
        sub.style,
        "", "0", "0", "0", "",
        sub.text.gsub(CUSTOM_BR_CODE, "\\n"),
      ].join(",")
    end

    event_section = ([
      "[Events]",
      "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ] + dialogues).join("\n")

    File.write(File.join(@dir, "subtitle.ass"), [script_info, style_section, event_section].join("\n\n"))
  end

  def write_srt_subtitle(subtitles)
    content = subtitles.each_with_index.map do |sub, i|
      [
        i.to_s,
        "#{format_srt_time(sub.start_time_sec)} --> #{format_srt_time(sub.end_time_sec)}",
        sub.text.gsub(CUSTOM_BR_CODE, "\n"),
      ].join("\n")
    end.join("\n\n")

    File.write(File.join(@dir, "subtitle.srt"), content)
  end

  private

  def format_ass_time(seconds)
    h  = (seconds / 3600).to_i
    m  = ((seconds % 3600) / 60).to_i
    s  = (seconds % 60).to_i
    cs = ((seconds - seconds.to_i) * 100).to_i
    format("%01d:%02d:%02d.%02d", h, m, s, cs)
  end

  def format_srt_time(seconds)
    h  = (seconds / 3600).to_i
    m  = ((seconds % 3600) / 60).to_i
    s  = (seconds % 60).to_i
    ms = ((seconds - seconds.to_i) * 1000).to_i
    format("%01d:%02d:%02d,%03d", h, m, s, ms)
  end
end
