ARG RUBY_VERSION=3.4.3
FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential curl ffmpeg fonts-noto-cjk git libvips libyaml-dev pkg-config sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

EXPOSE 80
ENTRYPOINT ["/rails/bin/docker-entrypoint-dev"]
CMD ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "80"]
